In [1]:
import torch

In [2]:
a = torch.tensor(4.)
a

tensor(4.)

In [3]:
a.dtype

torch.float32

In [4]:
b = torch.tensor([1., 2, 3, 4])
b

tensor([1., 2., 3., 4.])

Note that we get all the numbers as a floating point. It converts to the data type which is common for all here as floating point is broader than an integer we are normalized to floating point number rather than an integer.

In [5]:
c = torch.tensor([[5., 6],
                 [7, 8],
                 [9, 10]])
c

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [6]:
d = torch.tensor([
    [[11, 12, 13],
    [13, 14, 15]],
    [[15, 16, 17],
    [17, 18, 19.]]
])
d

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

In [7]:
print(a)
a.shape

tensor(4.)


torch.Size([])

In [8]:
print(b)
b.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [9]:
print(c)
c.shape

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


torch.Size([3, 2])

In [10]:
print(d)
d.shape

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])


torch.Size([2, 2, 3])

In [14]:
e = torch.tensor([[1, 2, 3],
                 [4, 5],
                 [6, 7]])
e

ValueError: expected sequence of length 3 at dim 1 (got 2)

We got a `ValueError` Because our shape that is the number of columns is not consistent. In the first row and third column we have extra data here. if we remove this `3` then we will be just fine

In [13]:
e = torch.tensor([[1, 2],
                 [4, 5],
                 [6, 7]])
e

tensor([[1, 2],
        [4, 5],
        [6, 7]])

See no errors 

## Tensor Operations and Gradients

In [15]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

#### Put this in an equation

In [16]:
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

so we do a simple arithemetic operation `3.0 * 4.0 + 5.0 = 17.0` 

In [18]:
# Compute Derivatives
y.backward()

In [20]:
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


If the `requires_grad` is set to `True` then only we are able to see the derivative of the equation.
### Note that for derivations we need to first derivate the equation using the `.backward()` method.

# Tensor Functions

In [25]:
f = torch.full((3, 2), 42, dtype=torch.int64)
f

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [26]:
g = torch.cat((c, f))
g

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])

In [27]:
# Compute sin of each element.
h = torch.sin(g)
h

tensor([[-0.9589, -0.2794],
        [ 0.6570,  0.9894],
        [ 0.4121, -0.5440],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [28]:
# Reshaping the shape of the tensor
i = h.reshape(3, 2, 2)
i

tensor([[[-0.9589, -0.2794],
         [ 0.6570,  0.9894]],

        [[ 0.4121, -0.5440],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])

# Torch with Numpy

In [29]:
import numpy as np

In [30]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [31]:
# Convert numpy to torch using the following
y = torch.from_numpy(x)
y

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [32]:
x.dtype, y.dtype

(dtype('int32'), torch.int32)

In [34]:
# Convert back to numpy from torch
z = y.numpy()
z

array([[1, 2],
       [3, 4]])

# Commiting Jupyter Notebook to JOVIAN

In [35]:
import jovian

<IPython.core.display.Javascript object>

In [36]:
jovian.commit(project="pytorch-basics-001")

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Please enter your API key ( from https://jovian.ai/ ):
API KEY: ········
[jovian] Creating a new project "hemanthhari2000/pytorch-basics-001"
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/hemanthhari2000/pytorch-basics-001


'https://jovian.ai/hemanthhari2000/pytorch-basics-001'