# Linear Regression using PyTorch Built-ins

In [1]:
import torch
import torch.nn as nn
import numpy as np

In [2]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [3]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

In [4]:
inputs.shape

torch.Size([15, 3])

In [5]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [6]:
from torch.utils.data import TensorDataset

In [7]:
train_ds = TensorDataset(inputs, targets)
train_ds[:]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.],
         [ 74.,  66.,  43.],
         [ 91.,  87.,  65.],
         [ 88., 134.,  59.],
         [101.,  44.,  37.],
         [ 68.,  96.,  71.],
         [ 73.,  66.,  44.],
         [ 92.,  87.,  64.],
         [ 87., 135.,  57.],
         [103.,  43.,  36.],
         [ 68.,  97.,  70.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.],
         [ 57.,  69.],
         [ 80., 102.],
         [118., 132.],
         [ 21.,  38.],
         [104., 118.],
         [ 57.,  69.],
         [ 82., 100.],
         [118., 134.],
         [ 20.,  38.],
         [102., 120.]]))

In [8]:
from torch.utils.data import DataLoader

In [9]:
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle = True)

In [10]:
for bat, (xb, yb) in enumerate(train_dl):
    print(f'batch: {bat+1}')
    print(xb)
    print(yb)
    print('='*40)

batch: 1
tensor([[103.,  43.,  36.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 87., 134.,  58.],
        [ 73.,  67.,  43.]])
tensor([[ 20.,  38.],
        [ 57.,  69.],
        [ 80., 102.],
        [119., 133.],
        [ 56.,  70.]])
batch: 2
tensor([[101.,  44.,  37.],
        [102.,  43.,  37.],
        [ 68.,  96.,  71.],
        [ 91.,  88.,  64.],
        [ 73.,  66.,  44.]])
tensor([[ 21.,  38.],
        [ 22.,  37.],
        [104., 118.],
        [ 81., 101.],
        [ 57.,  69.]])
batch: 3
tensor([[ 88., 134.,  59.],
        [ 68.,  97.,  70.],
        [ 69.,  96.,  70.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.]])
tensor([[118., 132.],
        [102., 120.],
        [103., 119.],
        [ 82., 100.],
        [118., 134.]])


In [11]:
# Define the Model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.1686, -0.2022,  0.5454],
        [ 0.2921,  0.3496, -0.1846]], requires_grad=True)
Parameter containing:
tensor([ 0.5671, -0.1382], requires_grad=True)


In [12]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.1686, -0.2022,  0.5454],
         [ 0.2921,  0.3496, -0.1846]], requires_grad=True),
 Parameter containing:
 tensor([ 0.5671, -0.1382], requires_grad=True)]

This `model.parameters()` gives us the detailed info about the parameters that the model has.

In [13]:
preds = model(inputs)
preds

tensor([[22.7777, 36.6706],
        [33.0189, 45.3939],
        [19.7733, 61.4162],
        [29.2457, 37.8564],
        [30.9654, 40.6584],
        [23.1484, 36.6130],
        [33.7664, 44.8597],
        [20.4872, 61.5236],
        [28.8750, 37.9139],
        [31.3422, 40.1818],
        [23.5252, 36.1364],
        [33.3896, 45.3363],
        [19.0258, 61.9503],
        [28.8689, 38.3330],
        [30.5946, 40.7160]], grad_fn=<AddmmBackward>)

# Loss Function

In [14]:
import torch.nn.functional as F

In [15]:
loss_fn = F.mse_loss

In [16]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(3381.0232, grad_fn=<MseLossBackward>)


# Optimizer

In [17]:
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

# Train the Model

In [25]:
# do the same as before

def fit(num_epochs, model, loss_fn, opt, train_dl):
    for epoch in range(num_epochs):
        for xb, yb in train_dl:
            pred = model(xb)
            loss = loss_fn(pred, yb)
            loss.backward()
            opt.step()
            opt.zero_grad()
        if (epoch+1) % 10 == 0:
            print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {round(loss.item(), 3)}')

# Fit the model

In [19]:
fit(1000, model, loss_fn, opt, train_dl)

Epoch [10/1000], Loss: 705.225
Epoch [20/1000], Loss: 493.784
Epoch [30/1000], Loss: 188.651
Epoch [40/1000], Loss: 153.483
Epoch [50/1000], Loss: 119.424
Epoch [60/1000], Loss: 76.852
Epoch [70/1000], Loss: 48.972
Epoch [80/1000], Loss: 46.256
Epoch [90/1000], Loss: 59.281
Epoch [100/1000], Loss: 44.165
Epoch [110/1000], Loss: 28.052
Epoch [120/1000], Loss: 40.906
Epoch [130/1000], Loss: 39.947
Epoch [140/1000], Loss: 18.283
Epoch [150/1000], Loss: 22.498
Epoch [160/1000], Loss: 17.42
Epoch [170/1000], Loss: 17.911
Epoch [180/1000], Loss: 14.814
Epoch [190/1000], Loss: 23.388
Epoch [200/1000], Loss: 6.167
Epoch [210/1000], Loss: 14.74
Epoch [220/1000], Loss: 20.113
Epoch [230/1000], Loss: 15.179
Epoch [240/1000], Loss: 3.834
Epoch [250/1000], Loss: 16.602
Epoch [260/1000], Loss: 9.638
Epoch [270/1000], Loss: 10.67
Epoch [280/1000], Loss: 7.345
Epoch [290/1000], Loss: 11.587
Epoch [300/1000], Loss: 6.37
Epoch [310/1000], Loss: 6.107
Epoch [320/1000], Loss: 2.143
Epoch [330/1000], Loss:

In [20]:
preds = model(inputs)
preds

tensor([[ 57.0451,  70.4021],
        [ 82.0250, 100.2273],
        [118.0895, 133.4540],
        [ 20.7879,  37.9258],
        [101.9742, 117.8352],
        [ 55.7951,  69.3181],
        [ 81.8865, 100.2656],
        [118.3807, 134.0260],
        [ 22.0379,  39.0098],
        [103.0856, 118.9576],
        [ 56.9065,  70.4404],
        [ 80.7751,  99.1433],
        [118.2281, 133.4157],
        [ 19.6765,  36.8034],
        [103.2241, 118.9193]], grad_fn=<AddmmBackward>)

In [21]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [22]:
model(torch.tensor([[75, 63, 44.]]))

tensor([[53.5668, 67.4634]], grad_fn=<AddmmBackward>)

In [23]:
# import jovian

In [24]:
# jovian.commit(project='pytorch_linear_regression_using_builtins')